language: ruby
cache: bundler
sudo: required

services:
- docker
rvm:
- 2.4
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y build-essential libcurl4-openssl-dev
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script:
- bundle exec rspec
- docker build -t owasp/glue . -f docker/glue/Dockerfile-raw --label COMMIT_SHA:$TRAVIS_COMMIT
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT --debug"
before_deploy:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
after_deploy:
- docker logout
deploy:
  - provider: rubygems
    api_key:
      secure: F/HpV5oaF0W0d0yhHd1oOgzJUxPXW/IGxLBXieyiqoyfae2kA6VoTvCijSz6tY4Fo7kYXQvwWouLWr/MokTRISO4pD3iwghfFQONtqjqBAB99+wGwJFARdIhVGAHTTlDoykgmh/nIYRwWMYvo/9sg+cq7RN6guMC88suaZ9AF3sweFNOiMiDvks7E0Id/6yyE2USlK8Lef03LaoTgylpB2raogKmDwQ6yx5JVBWUAzZnshSvQWst+o1CKQUGC8/U/1shjpPRmUlEAxLwdrkk9BYffHX2QdMYPzaBYU4zool/YypbjOHIws7izgJI3zUrbYVNyAwOfyaMQjYpnu2C9XGYVA7Fm5xCnJXkzfIP0jNhcoA7d55NedVLn3tFbsE1HgkC8tG3QephOmHJdW5oQy6+L4c1jkAQzV5HQPodBMHkSG0Zw7H28R67DSoIFIo76i6ak8Ina0KTZ7/mtu/O2UKN8sRLQW4+AE6yHRXQp3DsZxwdjoC+TyWEqpthFVHb9PeEJpxldd9r82lRyBGX8C4Gia265c4A4WfY675tzR6S9X6JxUnl0HkrLpOeg5lv5EfF2eg5ypM4sb5cVhD3dnyLY1EWVaJ8kZAb33JL75TFR8jQ+TVM0HqCMTiAw5dNQXxAMvGmcpOOVvHB/GpZMIDuxRfHZmgGQ9iJggGMl/I=
    gem: owasp-glue
    on:
      tags: true
      branch: master
      repo: OWASP/glue
  - provider: script
    script: docker tag owasp/glue owasp/glue:latest-raw && docker push owasp/glue:raw-latest
    on:
      branch: master
      repo: OWASP/glue
  - provider: script
    script: docker tag owasp/glue owasp/glue:$TRAVIS_TAG && docker push owasp/glue:$TRAVIS_TAG
    on:
      branch: master
      tags: true
      repo: OWASP/glue
env:
  global:
    - secure: idBRF6n/XLA25Z46aHBI4KaM+ljbzzD9L58JuASp/VBuViM07r0ASO0HDMMafiVuYpyBUXeo8f7/Kzb88z8fQUi3aTnMkOxsAl5PiygR0on7DQie1G78OKJ+wZ6NiEzYwFLrzVhjEXvFIsu8zZWtLfRNC+54HignxhIrdw0PEcsXbAE1UT1zR9zuBJfWrCtHGH6sQ6a57qiyGoOkjBnScDef5Tn0LgPT8WISy4Qb1AiAJDAnW9D8lF3sSWRbwysMjbIUTlTMqaZGpGVtTGiW75Vx60kY1qZ1dRZNm5U/QLlD3T8SAig6gYXGBXHgV1CR3S1JVNhX//Fk26HzTI5S3lNCw/h+qpSevdfqXZMaLSOJ5QF0920V1i+veUxSnd7BeFcCG6sxpVaHr/ztzptMSqyceYMEzmdpcDqXuPC+wn/U3QA4LWFW0PyfbWxrH9ibP4BaMEQNIHG1mByIDFLgZzB6zIQUQWPoB55DkmlRA1QC5Te+8JntvbVZF8qMk0Sv7lrg2ilTkFON7cHPE9y9wkaM5EhbdAwAl8cg6tDVeLrvmB6W+AuCFt1wgm46UEn8soSBNdYZThtfw7DvmUoFuMP/Nnmr9see6OFFnrSO4oslbbxLQAowWjnR1JzwXbrJcwrvA6d0Oy3C5byAduQoZCxN8d7SdnUuQeeSi1xVAzc=
    - DOCKER_USERNAME=owaspglueci